// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  free_text: dynamic(() => import("./FreeText")),
  hero: dynamic(() => import("./Hero")),
  latest_news: dynamic(() => import("./LatestNews")),
  list_news: dynamic(() => import("./ListNews")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
